import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//------------------------------------------------------
import NavBar from "./components/layout/navbar/NavBar";
import Header from "./components/layout/header/Header";
//------------------------------------------------------
const inter = Inter({ subsets: ["latin"] });
//------------------------------------------------------
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//------------------------------------------------------
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>  
        <div className="page">
          <Header/>
          <NavBar/>
          <div className="content">
            {children}
          </div>
          </div>
      </body>
    </html>
  );
};